version: "3.2"

services:
  # Command Central
  cc:
    image: ${REG}/cc-server:${TAG}
    ports:
      - "8091:8091"
    hostname: cc
    environment:
      - CC_PASSWORD
    volumes:
      - 'cce-conf:/opt/softwareag/profiles/CCE/conf'
      - 'cce-data:/opt/softwareag/profiles/CCE/data'
      - 'spm-conf:/opt/softwareag/profiles/SPM/conf'
      - 'spm-data:/opt/softwareag/profiles/SPM/data'

  # Hello World sample
  hello-world:
    image: ${REG}/hello-world:${TAG}
    build:
      context: hello-world/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
        - __hello_name=Container        # container specific build ARG
    hostname: hello-world
    environment:
      - CC_AUTO_REGISTER
      - HELLO_NAME=CONTAINER_INSTANCE   # container specific ENV var

  # Asset Build Environment
  abe:
    image: ${REG}/abe:${TAG}
    build:
      context: abe/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Asset Build Environment"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"

  # API Gateway
  apigw:
    image: ${REG}/apigw:${TAG}
    build:
      context: apigw/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=API Gateway"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "6555:5555"
      - "9072:9072"
    hostname: apigw
    environment:
      - CC_AUTO_REGISTER
      - JAVA_MIN_MEM=512
      - JAVA_MAX_MEM=512
      - apigw_elasticsearch_hosts=ids:9240
    stop_grace_period: 30s
    depends_on:
      - ids

  # Broker Server
  broker:
    image: ${REG}/broker:${TAG}
    build:
      context: broker/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Broker Server"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "6849:6849"
    hostname: broker
    environment:
      - CC_AUTO_REGISTER
      - BROKER_CONFIG_SIZE=64M
      - BROKER_DATA_SIZE=512M
    volumes:
      - 'broker-data:/opt/softwareag/Broker/data'
    stop_grace_period: 30s

  # Internal Data Store (Elasticsearch)
  ids:
    image: ${REG}/ids:${TAG}
    build:
      context: ids/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Internal Data Store"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "9240:9240"
    hostname: ids
    environment:
      - CC_AUTO_REGISTER
      - node.name=ids
      - discovery.seed_hosts=ids:9340
      - cluster.initial_master_nodes=ids
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - 'ids-data:/opt/softwareag/InternalDataStore/data'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stop_grace_period: 30s

  # Integration Server
  is:
    image: ${REG}/is:${TAG}
    build:
      context: is/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Integration Server"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "5555:5555"
    hostname: is
    environment:
      - CC_AUTO_REGISTER
      - JAVA_MIN_MEM=512
      - JAVA_MAX_MEM=512
    volumes:
      - 'is-cache:/opt/softwareag/IntegrationServer/instances/default/cacheStore'
      - 'is-db:/opt/softwareag/IntegrationServer/instances/default/db'
      - 'is-ds:/opt/softwareag/IntegrationServer/instances/default/DocumentStore'
      - 'is-xa:/opt/softwareag/IntegrationServer/instances/default/XAStore'
    stop_grace_period: 30s

  # Microservices Runtime
  msr:
    image: ${REG}/msr:${TAG}
    build:
      context: msr/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Microservices Runtime"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "5556:5555"
    hostname: msr
    environment:
      - CC_AUTO_REGISTER
      - JAVA_MIN_MEM=512m
      - JAVA_MAX_MEM=512m
    volumes:
      - './msr/runtime/autodeploy:/opt/softwareag/IntegrationServer/replicate/autodeploy'
      - './msr/runtime/application.properties:/opt/softwareag/IntegrationServer/application.properties'
      - 'msr-cache:/opt/softwareag/IntegrationServer/cacheStore'
      - 'msr-db:/opt/softwareag/IntegrationServer/db'
      - 'msr-xa:/opt/softwareag/IntegrationServer/XAStore'
    stop_grace_period: 30s

  # My webMethods Server
  mws:
    image: ${REG}/mws:${TAG}
    build:
      context: mws/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=My webMethods Server"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "8585:8585"
    hostname: mws
    environment:
      - CC_AUTO_REGISTER
      - JAVA_MIN_MEM=512
      - JAVA_MAX_MEM=512
      - MWS_DB_TYPE=postgresql
      - MWS_DB_URL=jdbc:wm:postgresql://mws-db:5432;databaseName=mws
      - MWS_DB_USERNAME=mws
      - MWS_DB_PASSWORD=mws
      - MWS_DB_NAME=mws
    stop_grace_period: 30s
    depends_on:
      - mws-db

  # My webMethods Server database (PostgreSQL)
  mws-db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mws
      - POSTGRES_PASSWORD=mws
      - POSTGRES_DB=mws
    volumes:
      - 'mws-db:/var/lib/postgresql/data'
    stop_grace_period: 30s

  # Terracotta Management Console
  tmc:
    image: ${REG}/tmc:${TAG}
    build:
      context: tmc/
      args:
        - BASE_IMAGE=${REG}/tsa:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Terracotta Management Console"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "9889:9889"
    hostname: tmc
    environment:
      - TSA_URL=http://tsa:9540
    stop_grace_period: 30s
    depends_on:
      - tsa

  # Terracotta Server
  tsa:
    image: ${REG}/tsa:${TAG}
    build:
      context: tsa/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Terracotta Server"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "9510:9510"
      - "9540:9540"
    hostname: tsa
    environment:
      - CC_AUTO_REGISTER
      - JAVA_MIN_MEM=128
      - JAVA_MAX_MEM=512
    volumes:
      - 'tsa-backup:/opt/softwareag/Terracotta/server/backup'
      - 'tsa-data:/opt/softwareag/Terracotta/server/data'
      - 'tsa-index:/opt/softwareag/Terracotta/server/index'
    stop_grace_period: 30s

  # Universal Messaging
  um:
    image: ${REG}/um:${TAG}
    build:
      context: um/
      args:
        - BUILDER_IMAGE=${REG}/cc-builder:${TAG}
        - BASE_IMAGE=${REG}/java:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Universal Messaging"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    ports:
      - "9000:9000"
    hostname: um
    environment:
      - CC_AUTO_REGISTER
      - JAVA_MIN_MEM=512
      - JAVA_MAX_MEM=512
    volumes:
      - 'um-data:/opt/softwareag/UniversalMessaging/server/default/data'
    stop_grace_period: 30s

volumes:
  broker-data:
  cce-conf:
  cce-data:
  ids-data:
  is-cache:
  is-db:
  is-ds:
  is-xa:
  msr-cache:
  msr-db:
  msr-xa:
  mws-db:
  spm-conf:
  spm-data:
  tsa-backup:
  tsa-data:
  tsa-index:
  um-data:
