version: "3.2"

services:
  base:
    image: ${REG}/base:${TAG}
    build:
      context: base/
      args:
        - BASE_IMAGE=centos:7

  java:
    image: ${REG}/java:${TAG}
    build:
      context: java/
      args:
        - BUILDER_IMAGE=${REG}/commandcentral-builder:${TAG}
        - BASE_IMAGE=${REG}/base:${TAG}
    depends_on: 
      - base
      - builder

  builder:
    image: ${REG}/commandcentral-builder:${TAG}
    ports:
      - 8091 # CCE
      - 8092 # SPM
    build:
      context: commandcentral-builder/
      args:
        - BUILDER_IMAGE=${CC_REG}/commandcentral-builder:${CC_TAG}
        - NODE_IMAGE=${CC_REG}/commandcentral-node:${TAG}
        - REPO_PRODUCT_URL=https://sdc.softwareag.com/dataservewebM105/repository
        - REPO_FIX_URL=https://sdc.softwareag.com/updates/prodRepo
        - REPO_USERNAME=${EMPOWER_USR}
        - REPO_PASSWORD=${EMPOWER_PSW}
