version: "3.2"

services:
  base:
    image: ${REG}/base:${TAG}
    build:
      context: base/
      args:
        - BASE_IMAGE=centos:7

  cc-server:
    image: ${REG}/cc-server:${TAG}
    build:
      context: cc-server/
      args:
        - BASE_IMAGE=${REG}/base:${TAG}
        - CC_INSTALLER
        - CC_INSTALLER_URL
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Command Central Server"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    depends_on: 
      - base

  cc-node:
    image: ${REG}/cc-node:${TAG}
    build:
      context: cc-node/
      args:
        - BUILDER_IMAGE=${REG}/cc-server:${TAG}
        - BASE_IMAGE=${REG}/base:${TAG}
        - CC_INSTALLER
        - CC_INSTALLER_URL
        - REPO_PRODUCT_URL
        - REPO_FIX_URL
        - REPO_USERNAME
        - REPO_PASSWORD
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Command Central Node"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    depends_on: 
      - cc-server
      - base

  cc-builder:
    image: ${REG}/cc-builder:${TAG}
    build:
      context: cc-builder/
      args:
        - BASE_IMAGE=${REG}/cc-server:${TAG}
        - NODE_IMAGE=${REG}/cc-node:${TAG}
        - REPO_PRODUCT_URL
        - REPO_FIX_URL
        - REPO_USERNAME
        - REPO_PASSWORD
        - LICENSES_URL
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Command Central Builder"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    depends_on:
      - cc-server
      - cc-node

  java:
    image: ${REG}/java:${TAG}
    build:
      context: java/
      args:
        - BUILDER_IMAGE=${REG}/cc-node:${TAG}
        - BASE_IMAGE=${REG}/base:${TAG}
      labels:
        - "org.opencontainers.image.licenses=SoftwareAG"
        - "org.opencontainers.image.revision=${IMAGE_REV:-}"
        - "org.opencontainers.image.title=Java base image"
        - "org.opencontainers.image.url=${IMAGE_URL:-}"
        - "org.opencontainers.image.vendor=SoftwareAG"
        - "org.opencontainers.image.version=${TAG}"
    depends_on: 
      - cc-node
      - base
