version: "3.2"

services:
  # API Gateway node 1
  apigw-1:
    image: ${REG}/apigw:${TAG}
    ports:
      - "5555:5555"
      - "9072:9072"
    hostname: apigw-1
    environment:
      - JAVA_MIN_MEM=512
      - JAVA_MAX_MEM=512
      - apigw_cluster_tsaUrls=tsa-1:9510,tsa-2:9510
      - apigw_elasticsearch_hosts=elasticsearch-1:9240,elasticsearch-2:9240
      - apigw_kibana_dashboardInstance=http://kibana-1:9405
      - apigw_terracotta_license_filename=terracotta-license.key
    stop_grace_period: 30s
    depends_on:
      - elasticsearch-1
      - kibana-1
      - tsa-1

  # API Gateway node 2
  apigw-2:
    image: ${REG}/apigw:${TAG}
    ports:
      - "5655:5555"
      - "9172:9072"
    hostname: apigw-2
    environment:
      - JAVA_MIN_MEM=512
      - JAVA_MAX_MEM=512
      - apigw_cluster_tsaUrls=tsa-1:9510,tsa-2:9510
      - apigw_elasticsearch_hosts=elasticsearch-1:9240,elasticsearch-2:9240
      - apigw_kibana_dashboardInstance=http://kibana-2:9405
      - apigw_terracotta_license_filename=terracotta-license.key
    stop_grace_period: 30s
    depends_on:
      - elasticsearch-2
      - kibana-2
      - tsa-2

  # API Gateway Data Store (Elasticsearch) node 1
  elasticsearch-1:
    image: ${REG}/apigw-es:${TAG}
    ports:
      - "9240:9240"
    hostname: elasticsearch-1
    environment:
      - node.name=elasticsearch-1
      - node.master=true
      - discovery.seed_hosts=elasticsearch-1:9340
      - cluster.initial_master_nodes=elasticsearch-1
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - 'elasticsearch-1-data:/opt/softwareag/InternalDataStore/data'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stop_grace_period: 30s

  # API Gateway Data Store (Elasticsearch) node 2
  elasticsearch-2:
    image: ${REG}/apigw-es:${TAG}
    ports:
      - "9340:9240"
    hostname: elasticsearch-2
    environment:
      - node.name=elasticsearch-2
      - node.master=false
      - discovery.seed_hosts=elasticsearch-1:9340
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - 'elasticsearch-2-data:/opt/softwareag/InternalDataStore/data'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stop_grace_period: 30s

  # Kibana node 1
  kibana-1:
    image: ${REG}/apigw-kibana:${TAG}
    ports:
      - "9405:9405"
    hostname: kibana-1
    environment:
      - elasticsearch.hosts=http://elasticsearch-1:9240
    stop_grace_period: 30s
    depends_on:
      - elasticsearch-1

  # Kibana node 2
  kibana-2:
    image: ${REG}/apigw-kibana:${TAG}
    ports:
      - "9505:9405"
    hostname: kibana-2
    environment:
      - elasticsearch.hosts=http://elasticsearch-2:9240
    stop_grace_period: 30s
    depends_on:
      - elasticsearch-2

  # Terracotta Server node 1
  tsa-1:
    image: ${REG}/tsa:${TAG}
    ports:
      - "9510:9510"
      - "9540:9540"
    hostname: tsa-1
    environment:
      - TC_NODE_NAME=tsa-1
      - TC_NODES=tsa-1,tsa-2
    volumes:
      - 'tsa-1-data:/opt/softwareag/Terracotta/server/data'
      - 'tsa-1-index:/opt/softwareag/Terracotta/server/index'

  # Terracotta Server node 2
  tsa-2:
    image: ${REG}/tsa:${TAG}
    ports:
      - "9610:9510"
      - "9640:9540"
    hostname: tsa-2
    environment:
      - TC_NODE_NAME=tsa-2
      - TC_NODES=tsa-1,tsa-2
    volumes:
      - 'tsa-2-data:/opt/softwareag/Terracotta/server/data'
      - 'tsa-2-index:/opt/softwareag/Terracotta/server/index'

volumes:
  elasticsearch-1-data:
  elasticsearch-2-data:
  tsa-1-data:
  tsa-1-index:
  tsa-2-data:
  tsa-2-index:
