name: CI

on: [push]

env:
  DOCKER_REGISTRY: docker.crespel.me
  DOCKER_REPO: sag

jobs:
  build_infra:
    runs-on: ubuntu-latest
    env:
      REPO_PRODUCT_URL: ${{ secrets.REPO_PRODUCT_URL }}
      REPO_FIX_URL: ${{ secrets.REPO_FIX_URL }}
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      LICENSES_URL: ${{ secrets.LICENSES_URL }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
        echo "REPO_PRODUCT_URL=${REPO_PRODUCT_URL:-https://sdc.softwareag.com/dataservewebM105/repository}" >> $GITHUB_ENV
        echo "REPO_FIX_URL=${REPO_FIX_URL:-https://sdc.softwareag.com/updates/prodRepo}" >> $GITHUB_ENV
    - name: Build images
      working-directory: infrastructure
      run: docker-compose build
    - name: Publish images
      working-directory: infrastructure
      run: docker-compose push

  build_abe:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build abe
    - name: Publish image
      working-directory: containers
      run: docker-compose push abe

  build_apigw:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build apigw
    - name: Publish image
      working-directory: containers
      run: docker-compose push apigw

  build_broker:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build broker
    - name: Publish image
      working-directory: containers
      run: docker-compose push broker

  build_ids:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: |
        sudo sysctl -w vm.max_map_count=262144
        docker-compose build ids
    - name: Publish image
      working-directory: containers
      run: docker-compose push ids

  build_is:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build is
    - name: Publish image
      working-directory: containers
      run: docker-compose push is

  build_msr:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build msr
    - name: Publish image
      working-directory: containers
      run: docker-compose push msr

  build_mws:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build mws
    - name: Publish image
      working-directory: containers
      run: docker-compose push mws

  build_um:
    runs-on: ubuntu-latest
    needs: build_infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${DOCKER_REGISTRY}
        echo "REG=${DOCKER_REGISTRY}/${DOCKER_REPO}" >> $GITHUB_ENV
    - name: Build image
      working-directory: containers
      run: docker-compose build um
    - name: Publish image
      working-directory: containers
      run: docker-compose push um
